lugares = ['Italia' , 'Francia' , 'Canadá' , 'Turquía' , 'China']
print(f"\n{' '.join(lugares)} \n")
print(f"{' '.join(sorted(lugares))}\n")
print(f"{' '.join(lugares)} \n")
print(f"{' '.join(sorted(lugares , reverse =True))}\n")
print(f"{' '.join(lugares)} \n")
lugares.reverse()
print(f"{' '.join(lugares)} \n")
lugares.reverse()
print(f"{' '.join(lugares)} \n")
lugares.sort()
print(f"{' '.join(lugares)} \n")
lugares.sort(reverse =True)
print(f"{' '.join(lugares)} \n")